@url = http://localhost:5002
@customerId = 1bfa84008-649a-475c-a6a0-b62f24c13398
@state = valid

###
GET {{url}}/customers

###
GET {{url}}/customers/{{customerId}}

###
GET {{url}}/customers/{{customerId}}/state

###
POST {{url}}/customers
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "fullname": "John Doe1",
  "address": "New York City, Street XYZ1"
}

###
PUT {{url}}/customers/{{customerId}}/state/{{state}}
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "state": "{{state}}"
}