name: publish 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
        
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    
    - name: Print slug/short variables
      run: |
        echo "Slug variables"
        echo "   ref        : ${{ env.GITHUB_REF_SLUG }}"
        echo "   head ref   : ${{ env.GITHUB_HEAD_REF_SLUG }}"
        echo "   base ref   : ${{ env.GITHUB_BASE_REF_SLUG }}"
        echo "   event ref  : ${{ env.GITHUB_EVENT_REF_SLUG }}"
        echo "   repository : ${{ env.GITHUB_REPOSITORY_SLUG }}"
        echo "Slug URL variables"
        echo "   ref        : ${{ env.GITHUB_REF_SLUG_URL }}"
        echo "   head ref   : ${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
        echo "   base ref   : ${{ env.GITHUB_BASE_REF_SLUG_URL }}"
        echo "   event ref  : ${{ env.GITHUB_EVENT_REF_SLUG_URL }}"
        echo "   repository : ${{ env.GITHUB_REPOSITORY_SLUG_URL }}"
        echo "Short SHA variables"
        echo "   sha        : ${{ env.GITHUB_SHA_SHORT }}"
        
    - name: build
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        Branch_Name: ${{ env.GITHUB_REF_SLUG }}
        Github_ID: ${{ env.Github_ID }}
      run: |
       sh ./scripts/dockerize.sh
    
 
      
